# OpenSSL ########################################################################

[OpenSSL]
disabled_targets = ["ios"]
version = "1.1.1g"

# zlib ########################################################################

[zlib]
version = "1.3.1"
install_from_source = true

[zlib.win]
install_from_source = true
static_msvc_runtime = true

# Python ########################################################################

[Python]
version = "3.11.6"

[Python.macos]
install_host_from_source = false

[Python.ios]
install_host_from_source = true

[Python.win]
install_host_from_source = false

# SIP ########################################################################

[SIP]
# version = "12.15.0"
module_name = "PyQt5.sip"
# Required for pyqtdeploy-3.3.0
abi_major_version = 12

# Qt ########################################################################

[Qt]
version = "5.15.16"
edition = "opensource"
skip = [
    "qt3d",
    "qtactiveqt",
    "qtcanvas3d",
    "qtgamepad",
    "qtlocation",
    "qtremoteobjects",
    "qtscript",
    "qtserialbus",
    "qtserialport",
    "qtspeech",
    "qtwayland",
    "qtwebchannel",
    "qtwebengine",
    "qtwebglplugin",
    "qtwebsockets",
    "qtwebview",
    "qtlottie",
    "qtdatavis3d",
    "qtconnectivity",
    "qtcharts",
    "qtandroidextras",
    "qtdoc",
    "qtnetworkauth",
    "qtqa",
    "qtrepotools",
    "qtscxml",
    "qtsensors",
    "qtsvg",
    "qttools",
    "qttranslations",
    "qtx11extras",
    "qtxmlpatterns",
    "qtmultimedia",
    "qtpurchasing",
    "qtimageformats",
    "qtquick3d"
]

[Qt.macos]
install_from_source = true # required for static build
ssl = "openssl-linked"
configure_options = [
    "--verbose",
    "-debug-and-release",
    "-nomake", "examples",
    "-nomake", "tests",
    "-no-sql-mysql",
    "-no-sql-psql"
]

[Qt.win]
ssl = "openssl-linked"
static_msvc_runtime = true
install_from_source = true
configure_options = [
    "-debug-and-release",
    "-nomake", "examples",
    "-nomake", "tests",
    "-opengl", "desktop", "-no-angle",
    "-no-sql-mysql",
    "-no-sql-psql"
]

[Qt.ios]
version = "5.15.2"
install_from_source = false
ssl = "securetransport"

# PyQt ########################################################################

[PyQt]
version = "5.15.11"
installed_modules = [ ]

[PyQt.macos]
installed_modules = [
    "QtCore", "QtGui", "QtNetwork", "QtPrintSupport", "QtWidgets",
    "QtMacExtras", "QtQml", "QtQuick", "QtQuickWidgets"
]

[PyQt.ios]
disabled_features = [
    "PyQt_Desktop_OpenGL", "PyQt_MacOSXOnly",
    "PyQt_MacCocoaViewContainer", "PyQt_Printer",
    "PyQt_PrintDialog", "PyQt_PrintPreviewDialog",
    "PyQt_PrintPreviewWidget", "PyQt_Process",
    "PyQt_NotBootstrapped"
]
installed_modules = [
    "QtCore", "QtGui", "QtNetwork", "QtWidgets",
    "QtMacExtras", "QtQml", "QtQuick", "QtQuickWidgets"
]

[PyQt.win]
disabled_features = [ "PyQt_Desktop_OpenGL" ]
installed_modules = [
    "QtCore", "QtGui", "QtNetwork", "QtPrintSupport", "QtWidgets",
    "QtQml", "QtQuick", "QtQuickWidgets", "QtWinExtras"
]


# Misc Third-Party ####################################################################

[six]
plugin = "wheel"
wheel = "six-1.14.0-py2.py3-none-any.whl"
version = "1.14.0"

[appdirs]
plugin = "wheel"
wheel = "appdirs-1.4.4-py2.py3-none-any.whl"
version = "1.4.4"

[dateutil]
plugin = "wheel"
project = "python-dateutil"
wheel = "python_dateutil-2.8.2-py2.py3-none-any.whl"
version = "2.8.2"

[sortedcontainers]
plugin = "wheel"
wheel = "sortedcontainers-2.2.2-py2.py3-none-any.whl"
version = "2.2.2"

[xlsxwriter]
plugin = "wheel"
wheel = "XlsxWriter-0.9.8-py2.py3-none-any.whl"
version = "0.9.8"

# App Modules ########################################################################

[btcopilot]
version = "1.0.0"

[_pkdiagram]
version = "1.0.0"


