# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Cache Test

on:
  push:
    branches: [ cache-test ]

jobs:
  cache-test:
    runs-on: macos-12

    steps:
              
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Cache Homebrew
      id: cache-homebrew
      uses: actions/cache@v2
      with:
        path: |
          /usr/local/Homebrew
          /usr/local/Cellar
          /usr/local/opt
        key: homebrew-${{ runner.os }}
        restore-keys: |
          homebrew-${{ runner.os }}-

    - name: Update Homebrew
      run: brew update

    - name: brew install qt@5 create-dmg
      run: |
          brew install qt@5 create-dmg

    - name: Save Homebrew cache
      if: always()
      uses: actions/cache@v2
      with:
        path: |
          /usr/local/Homebrew
          /usr/local/Cellar
          /usr/local/opt
        key: homebrew-${{ runner.os }}
