# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build macOS

on:
  push:
    branches: [ 2.0.0 ]

# defaults:
#   run:
#     working-directory: /Users/patrick/dev/familydiagram

jobs:
  build-osx:
    # x86 w/ python-3.12.5
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
    runs-on: macos-12

    env:
      FD_BUILD_APPLE_ID: "${{ secrets.FD_BUILD_APPLE_ID }}"
      FD_BUILD_APPLE_ID_PASSWORD: "${{ secrets.FD_BUILD_APPLE_ID_PASSWORD }}"
      FD_BUILD_PROVISIONING_PROFILE_BASE64: "${{ secrets.FD_BUILD_PROVISIONING_PROFILE_BASE64 }}"
      FD_BUILD_CERTIFICATE_BASE64: "${{ secrets.FD_BUILD_CERTIFICATE_BASE64 }}"
      FD_BUILD_PRIVATE_KEY_BASE64: "${{ secrets.FD_BUILD_PRIVATE_KEY_BASE64 }}"
      FD_BUILD_CERTIFICATE_PASSWORD: "${{ secrets.FD_BUILD_CERTIFICATE_PASSWORD }}"
      FD_BUILD_AC_AUTH_KEY_ID: "${{ secrets.FD_BUILD_AC_AUTH_KEY_ID }}"
      FD_BUILD_AC_AUTH_KEY_BASE64: "${{ secrets.FD_BUILD_AC_AUTH_KEY_BASE64 }}"
      FD_BUILD_AC_AUTH_KEY_ISSUER: "${{ secrets.FD_BUILD_AC_AUTH_KEY_ISSUER }}"
      FD_BUILD_PEPPER: "${{ secrets.FD_BUILD_PEPPER }}"
      FD_BUILD_BUGSNAG_API_KEY: "${{ secrets.FD_BUILD_BUGSNAG_API_KEY }}"

    steps:
              
    - uses: actions/checkout@v2
      with:
        submodules: true

    # # Will provide an SSH command in the logs that you can use to access the runner.
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3        

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4
        # architecture: 'x64'
        cache: 'pipenv'
    - run: |
        pip install pipenv
        pipenv install
    
    # Probably a better way: https://github.com/jurplel/install-qt-action
    - name: brew install create-dmg
      run: |
        brew install qt@5 create-dmg
        echo "/usr/local/opt/qt@5/bin" >> $GITHUB_PATH

    - name: Setup _pkdiagram caching
      id: cache-_pkdiagram
      uses: actions/cache@v2
      with:
        path: |
          pkdiagram/_pkdiagram/build
        key: _pkdiagram-${{ runner.os }}-${{ hashFiles('./pkdiagram/_pkdiagram/sip/*.sip', './pkdiagram/_pkdiagram/*.h', './pkdiagram/_pkdiagram/*.cpp') }}
    
    - name: sip-build for _pkdiagram
      if: steps.cache-_pkdiagram.outputs.cache-hit != 'true'
      run: |
        echo "/usr/local/opt/qt@5/bin" >> $GITHUB_PATH
        cd pkdiagram/_pkdiagram && pipenv run sip-build
        
    - name: Setup sysroot caching
      id: cache-sysroot
      uses: actions/cache@v2
      with:
        path: ./sysroot/sysroot-macos-64
        key: sysroot-macOS-2
        # key: sysroot-${{ runner.os }}-${{ hashFiles('./sysroot/sysroot.toml') }}
    
    - name: Build sysroot
      if: steps.cache-sysroot.outputs.cache-hit != 'true'
      run: |
        echo "/usr/local/opt/qt@5/bin" >> $GITHUB_PATH
        wget -L "https://www.zlib.net/fossils/zlib-1.2.11.tar.gz" -P ./sysroot/
        which qmake
        pipenv run pyqtdeploy-sysroot --target macos-64 --verbose sysroot/sysroot.toml
  
    # - name: Build app
    #   run: |
    #     pipenv run bin/build.sh

    # - name: Verify app
    #   run: |
    #     build/osx/Release/Family\ Diagram.app/Contents/MacOS/Family\ Diagram --version

    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: familydiagram-macos
    #     path: build/osx/Release/Family Diagram.dmg
  