name: Build Windows

on:
  push:
    branches:
      - 2.0.0

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4
        cache: 'pipenv'

    - name: Install pipenv
      run: python -m pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev

    # - name: Install Qt5
    #   run: |
    #     choco install qt5-default -y
    #     $env:PATH="C:\Qt\5.15.2\mingw81_64\bin;$env:PATH"

    - name: Set up Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'  # Specify the Qt version you need
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        # modules: 'qtbase qtdeclarative qtgraphicaleffects qtimageformats qtlocation qtmacextras qtpurchasing qtquickcontrols qtquickcontrols2'
        modules: 'qtbase'

    - name: Verify qmake
      run: |
        # $env:PATH="C:\Qt\5.15.2\mingw81_64\bin;$env:PATH"
        $env:PATH="C:\Qt\5.15.2\msvc2019_64\bin;$env:PATH"
        qmake --version        

    - name: Setup _pkdiagram caching
      id: cache-_pkdiagram
      uses: actions/cache@v2
      with:
        path: |
          pkdiagram/_pkdiagram/build
        key: _pkdiagram-${{ runner.os }}-${{ hashFiles('./pkdiagram/_pkdiagram/sip/*.sip', './pkdiagram/_pkdiagram/*.h', './pkdiagram/_pkdiagram/*.cpp') }}
    
    - name: sip-build for _pkdiagram
      if: steps.cache-_pkdiagram.outputs.cache-hit != 'true'
      run: |
        # $env:PATH="C:\Qt\5.15.2\mingw81_64\bin;$env:PATH"
        $env:PATH="C:\Qt\5.15.2\msvc2019_64\bin;$env:PATH"
        cd pkdiagram/_pkdiagram && pipenv run sip-build

    - name: Build app
      run: |
          pipenv run bin/build.bat
  
  