name: Build Windows

on:
  push:
    branches:
      - 2.0.0

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4
        cache: 'pipenv'

    - name: Install pipenv
      run: python -m pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev

    # - name: Install Visual Studio Build Tools
    #   run: |
    #     choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional" -y

    # - name: Install Qt5
    #   run: |
    #     choco install qt5-default -y
    #     $env:PATH="C:\Qt\5.15.2\mingw81_64\bin;$env:PATH"

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; `
        [System.Net.ServicePointManager]::SecurityProtocol = `
        [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install 7zip
      run: choco install 7zip -y

    - name: Download Qt Online Installer
      run: curl --fail -Lo qt-installer.exe "https://download.qt.io/official_releases/qt/5.15/5.15.2/qt-opensource-windows-x86-5.15.2.exe"

    - name: Install Qt
      run: |
        dir
        Start-Process -FilePath qt-installer.exe -ArgumentList " --script build/win32-config/qt-installer-noninteractive.qs" -NoNewWindow -Wait
          
    - name: Set up Qt environment variables
      run: |
        echo "C:\Qt\5.15.2\msvc2019_64\bin" >> $env:GITHUB_PATH
        echo "C:\Qt\5.15.2\msvc2019_64\include" >> $env:GITHUB_ENV

    - name: Verify qmake
      run: |
        qmake --version        
      shell: cmd

    - name: Setup _pkdiagram caching
      id: cache-_pkdiagram
      uses: actions/cache@v2
      with:
        path: |
          pkdiagram/_pkdiagram/build
        key: _pkdiagram-${{ runner.os }}-${{ hashFiles('./pkdiagram/_pkdiagram/sip/*.sip', './pkdiagram/_pkdiagram/*.h', './pkdiagram/_pkdiagram/*.cpp') }}
    
    - name: sip-build for _pkdiagram
      if: steps.cache-_pkdiagram.outputs.cache-hit != 'true'
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cd pkdiagram/_pkdiagram && pipenv run sip-build
      shell: cmd

    - name: Build app
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        pipenv run bin/build.bat
      shell: cmd
  
  