# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches:
      - 2.0.0
    # tags:
    #   - 'v*.*.b*'

jobs:
  test:

    runs-on: macos-12

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout code
      uses: actions/checkout@v2
      repository: patrickkidd/famildiagram-server
      path: famildiagram-server

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4
        # architecture: 'x64'
        cache: 'pipenv'
    - run: |
        pip install pipenv
        pipenv install --dev --verbose
  
    # It is faster to install homebrew than to restore from cache
    - name: brew install qt@5 create-dmg
      run: |
        brew install qt@5 create-dmg

    ## Build
    
    - name: sip-build for _pkdiagram
      if: steps.cache-_pkdiagram.outputs.cache-hit != 'true'
      run: |
        export PATH="/usr/local/opt/qt@5/bin:${PATH}"
        which qmake
        pipenv run cmake .
        pipenv run make

    - name: Write build config
      run: |
        pipenv run python bin/update_build_info.py
    
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)/familydiagram-server"
        echo $PYTHONPATH
        pipenv run pytest -svv ./tests
