# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  # push:
  #   branches:
  #     - 2.0.0
    # tags:
    #   - 'v*.*.b*'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Enable SSH via tmate (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  test:

    runs-on: macos-12

    steps:
    - name: Checkout patrickkidd/famildiagram
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Checkout patrickkidd/famildiagram-server
      uses: actions/checkout@v2
      with:
        repository: patrickkidd/familydiagram-server
        path: familydiagram-server
        ref: fdserver-refactor
        submodules: true
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4
        # architecture: 'x64'
        # cache: 'pipenv'
    - run: |
        pip install pipenv
        mkdir .venv
        pipenv install --dev
        pipenv run which sip-install
  
    # It is faster to install homebrew than to restore from cache
    - name: brew install qt@5 create-dmg
      run: |
        brew install qt@5 create-dmg

    ## Build
    
    - name: sip-install for vedanaprivate
      run: |
        export PATH="/usr/local/opt/qt@5/bin:${PATH}"        
        which qmake
        rm ./familydiagram-server/Pipfile*
        cd ./familydiagram-server/vedanaprivate
        pipenv run which sip-install
        pipenv run sip-install

        export PYQT5_DIR="/Users/runner/work/familydiagram/familydiagram/.venv/lib/python3.10/site-packages/PyQt5/Qt5"
        install_name_tool -add_rpath $PYQT5_DIR/lib /Users/runner/work/familydiagram/familydiagram/.venv/lib/python3.10/site-packages/_vedanaprivate.cpython-310-darwin.so
        install_name_tool -change /usr/local/opt/qt@5/lib/QtCore.framework/Versions/5/QtCore @rpath/QtCore.framework/Versions/5/QtCore /Users/runner/work/familydiagram/familydiagram/.venv/lib/python3.10/site-packages/_vedanaprivate.cpython-310-darwin.so
        install_name_tool -change /usr/local/opt/qt@5/lib/QtGui.framework/Versions/5/QtGui @rpath/QtGui.framework/Versions/5/QtGui /Users/runner/work/familydiagram/familydiagram/.venv/lib/python3.10/site-packages/_vedanaprivate.cpython-310-darwin.so
        install_name_tool -change /usr/local/opt/qt@5/lib/QtWidgets.framework/Versions/5/QtWidgets @rpath/QtWidgets.framework/Versions/5/QtWidgets /Users/runner/work/familydiagram/familydiagram/.venv/lib/python3.10/site-packages/_vedanaprivate.cpython-310-darwin.so
        otool -L /Users/runner/work/familydiagram/familydiagram/.venv/lib/python3.10/site-packages/_vedanaprivate.cpython-310-darwin.so

    - name: sip-install for _pkdiagram
      run: |
        export PATH="/usr/local/opt/qt@5/bin:${PATH}"
        which qmake
        pipenv run cmake .
        pipenv run make

        export PYQT5_DIR="/Users/runner/work/familydiagram/familydiagram/.venv/lib/python3.10/site-packages/PyQt5/Qt5"
        install_name_tool -add_rpath $PYQT5_DIR/lib /Users/runner/work/familydiagram/familydiagram/.venv/lib/python3.10/site-packages/_pkdiagram.cpython-310-darwin.so
        install_name_tool -change /usr/local/opt/qt@5/lib/QtCore.framework/Versions/5/QtCore @rpath/QtCore.framework/Versions/5/QtCore /Users/runner/work/familydiagram/familydiagram/.venv/lib/python3.10/site-packages/_pkdiagram.cpython-310-darwin.so
        install_name_tool -change /usr/local/opt/qt@5/lib/QtGui.framework/Versions/5/QtGui @rpath/QtGui.framework/Versions/5/QtGui /Users/runner/work/familydiagram/familydiagram/.venv/lib/python3.10/site-packages/_pkdiagram.cpython-310-darwin.so
        install_name_tool -change /usr/local/opt/qt@5/lib/QtWidgets.framework/Versions/5/QtWidgets @rpath/QtWidgets.framework/Versions/5/QtWidgets /Users/runner/work/familydiagram/familydiagram/.venv/lib/python3.10/site-packages/_pkdiagram.cpython-310-darwin.so
        otool -L /Users/runner/work/familydiagram/familydiagram/.venv/lib/python3.10/site-packages/_pkdiagram.cpython-310-darwin.so

    - name: Write build config
      run: |
        pipenv run python bin/update_build_info.py
    
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      if: ${{ ! inputs.debug_enabled }}
      run: |
        export PYTHONPATH="$(pwd)/familydiagram-server"
        pipenv run pytest -svv ./tests

    # Will provide an SSH command in the logs that you can use to access the runner.
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      # if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      if: ${{ inputs.debug_enabled }}

