name: Upload Release Artifacts

on:
  workflow_run:
    workflows: 
      - "Build macOS"
      - "Build Windows"
    types:
      - completed

jobs:
  upload-release:
    runs-on: ubuntu-latest

    steps:
    - name: Get Version
      run: |
        echo "version=`pipenv run python -c "import sys; sys.path.insert(0, './pkdiagram'); import version; print(version.VERSION)"`" >> $GITHUB_ENV
        echo $version

    - uses: actions/download-artifact@v2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.version }}
        release_name: ${{ env.version }}
        draft: false
        prerelease: false

    - name: Upload macOS Build
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Family Diagram.dmg
        asset_name: Family Diagram ${{ env.version }}.dmg
        asset_content_type: application/x-apple-diskimage

    - name: Upload Windows Build
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Family Diagram.zip
        asset_name: Family Diagram ${{ env.version }}.zip
        asset_content_type: application/vnd.microsoft.portable-executable