name: Update AppCast

on:
  release:
    types:
      - published  # Trigger when a new release is published
  workflow_dispatch:

jobs:
  update-appcast:
    runs-on: ubuntu-latest

    steps:

      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Generate appcast.xml
        id: get_release
        run: |
          python bin/github_releases_2_appcast.py

      - name: Push appcast.xml to familydiagram.com/appcast.xml
        env:
          FAMILYDIAGRAM_COM_SSH_PRIVATE_KEY: ${{ secrets.FAMILYDIAGRAM_COM_SSH_PRIVATE_KEY }}
        run: |
          echo "${FAMILYDIAGRAM_COM_SSH_PRIVATE_KEY}" > private_key
          chmod 600 private_key
          mkdir -p ~/.ssh
          ssh-keyscan -H familydiagram.com >> ~/.ssh/known_hosts
          scp -i private_key appcast.xml patrick@familydiagram.com:/var/www/html/appcast.xml
          rm private_key
